### ISSUE TITLE
Python breaks wordcloud_cli

### ISSUE THREAD

**Issue by nicholasdille** [nicholasdille/docker-setup#6156]
```plaintext
Traceback (most recent call last):
  File "/home/dillen/.shiv/wordcloud_cli_964b358828d7d7a1f8121cc1e621e8f251bf90a358316e49d3d7301f6b7f3a59/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/dillen/.shiv/wordcloud_cli_964b358828d7d7a1f8121cc1e621e8f251bf90a358316e49d3d7301f6b7f3a59/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/dillen/.shiv/wordcloud_cli_964b358828d7d7a1f8121cc1e621e8f251bf90a358316e49d3d7301f6b7f3a59/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /home/dillen/.shiv/wordcloud_cli_964b358828d7d7a1f8121cc1e621e8f251bf90a358316e49d3d7301f6b7f3a59/site-packages/numpy/core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyObject_SelfIter
```

**Comment by nicholasdille** [comment]
Migrated to https://github.com/uniget-org/tools/issues/62
